[package]
name = "profilers"
version = "0.0.0"
authors = ["Noah Rosenzweig <rosenzweig.noah@gmail.com>"]
edition = "2018"

[dependencies]
clap      = "2.33.0"
dirs      = "2.0.2"
serde     = { version = "1.0.104", features = ["derive"] }
structopt = "0.3.5"
toml      = "0.5.5"
